### ISSUE TITLE
windows 8.1 & Windows 2008 r2: ZeroMQ 4.0.4

### ISSUE THREAD

**Issue by csk1nner** [Open-Transactions/opentxs#602]
Hello Gang,

Trying to build out a Windows 2008 R2 version or a Windows 8.1 version.  Running into a problem with the ZeroMQ 4.0.4 bits:
---
Doxygen: graphviz not found - graphs disabled
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)
-- Could NOT find PythonInterp (missing:  PYTHON_EXECUTABLE)
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE)
-- Could NOT find ZEROMQ (missing:  ZEROMQ_LIBRARIES)
-- version: 3.0.1
-- install: C:/Program Files (x86)/opentxs
CMake Error: The following variables are used in this project, but they are set
to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake file
s:
ZEROMQ_LIBRARIES (ADVANCED)
    linked by target "czmq" in directory C:/Builds/Open Transactions/application
s/opentxs/deps/czmq
--

I've tried the x86 and the 64 bit version of ZeroMQ 4.0.4 and get the same result.  Everything else builds fine up to this point.

Any ideas?

Cheers,

Caleb

**Comment by ychaim** [comment]
You have to install Doxygen and ZeroMq I guess.

**Comment by csk1nner** [comment]
I stopped my windows build effort.  Moved to Ubuntu 14.

Thanks,

C

**Comment by yamamushi** [comment]
I've reopened this issue because I am currently working on getting opentxs to build in Windows, and with the help of a particular person in IRC I was able to get a Visual Studio project file generated and building (albeit not completely finished yet).

Specifically in reference to the issues you're reporting about ZMQ, this line should help you figure out how to get CMake to find it properly:

cmake -D PROTOBUF_INCLUDE_DIR="C:\protobuf\include" -D PROTOBUF_LIBRARY="C:\protobuf\libprotobuf\libprotobuf.lib" -D ZEROMQ_INCLUDE_DIRS="C:\Program Files\ZeroMQ 4.0.4\include" -D ZEROMQ_LIBRARIES="C:\Program Files\ZeroMQ 4.0.4\lib\libzmq-v120-mt-gd-4_0_4.lib" ..

Also, make sure you are grabbing ZMQ (and the other dependencies) from the links referenced in the documentation.

**Comment by yamamushi** [comment]
This is related to #572 , and I am closing this issue to narrow down the resolution into that one.
